### ISSUE TITLE
Error on import {shallow} from 'preact-render-spy';

### ISSUE THREAD

**Issue by keemor** [mzgoddard/preact-render-spy#41]
When I import:
`import {shallow} from 'preact-render-spy';`

I get error from babel:
```
ERROR in ./node_modules/preact-render-spy/index.js
Module build failed: ReferenceError: [BABEL] [cut]node_modules\preact-render-spy\index.js: Unkn
own option: [cut]node_modules\preact\dist\preact.js.h. Check out http://babeljs.io/docs/usage/o
ptions/ for more information about options.
```
my .babelrc
```
{
    "compact": "false",
    "presets": ["env"],
    "plugins": [
        "transform-decorators-legacy",
        "transform-object-rest-spread",
        "transform-object-assign",
        ["transform-react-jsx", { "pragma": "h" }],
        "transform-react-jsx-source"
    ]
}
```

Any suggestions?

**Comment by gnarf** [comment]
Looks like this might be a TypeScript issue? What version of preact?

**Comment by gnarf** [comment]
honestly though, this error is very confusing, I'm not sure what it could possibly be erroring about

**Comment by gnarf** [comment]
Hrm... I think I've figured this out!

Are you letting babel transpile your node_modules?  We don't actually need you to run babel on our library for it to work, so you should possibly disable it for that subdirectory.

We use the `babel-preset-preact` in our [`.babelrc`](https://github.com/mzgoddard/preact-render-spy/blob/master/.babelrc), which is bundled into our release package. 

This means when you `import` preact-render-spy, babel will try to load this preset to transpile our stuff.

I think we could possibly fix this by removing the `.babelrc` from our dist bundle in `.npmignore` but in order to make sure it **would** solve your problem, could you try `rm node_modules/preact-render-spy/.babelrc` and see if it fixes this problem for you?

Assuming it does, I'll update our npm ignore file to avoid publishing the `.babelrc` in the future.
